name: admg_app
description: "Aplicativo ADMG - Gerenciamento de Avisos e Pedidos de Oração"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true